### ISSUE TITLE
Sensitive data publicily exposed via php-info.php

### ISSUE THREAD

**Issue by nescafe2002** [emoncms/emoncms-docker#16]
Issue: environment variables containing sensitive info (passwords) are publicily exposed in the following scenario:

- Emoncms is installed in Docker using the documented method via docker-compose
- Emoncms is behind a reverse proxy, e.g. jwilder/nginx-proxy

Example dockerfile (docker-compose.prod.yml w/ VIRTUAL_HOST w/o ports):
```
# production / deployment / clean testing enviroment setup

version: '2'
services:

  web:
    #ports:
      # Expose Emoncms to the world on port 80
      #- 80:80
    env_file:
     # Use .env with secure db credentials (needs creating), ignored by git
     - '.docker-env'
    restart: always
    environment:
      # Set production enviroment variable flag, not currently used for anything but might be of use in the future
      PRODUCTION: 'true'
      # Used by nginx-proxy
      VIRTUAL_HOST: 'my-emoncms.company.com'
    
  db:
    restart: always
    env_file:
     - '.docker-env'

```

By accessing the url http://my-emoncms.company.com/php-info.php interally **or externally**, all info from .docker-env is exposed:

| Variable | Value |
| --- | --- |
| MYSQL_HOST | db |
| MYSQL_PORT | 3306 |
| MYSQL_DATABASE | emoncms |
| MYSQL_USER | emoncms |
| MYSQL_PASSWORD | YOUR_SECURE_PASSWORD |
| MYSQL_RANDOM_ROOT_PASSWORD | yes |
| REDIS_ENABLED | true |
| REDIS_HOST | redis |
| REDIS_PORT | 6379 |
| REDIS_PREFIX | 'emoncms' |
| MQTT_ENABLED | false |
| MQTT_HOST | localhost |
| MQTT_USER | YOUR_MQTT_USER |
| MQTT_PASSWORD | YOUR_MQTT_PASSWORD |
| MQTT_BASETOPIC | emon |
| VIRTUAL_HOST | my-emoncms.company.com |

This works externally due to nature of reverse proxy (requests are always originating from a local ip).

I would recommend removing php-info.php from the docker installation set. But, rather remove it from the general deployment set because it isn't necessary for normal operation and users could point /var/www/html to a currently checked out release (with php-info.php).
